import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <style>{`
        html, body {
          height: 100%;
        }
        body {    
          margin: 0px;
          padding: 0px;
        }
        #content-wrap {
          height: 100%;
          display: flex;
          flex-direction: row;
          justify-content: center;
        }
      `}</style>
      <html lang="en">
        <Header />
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <div id="content-wrap">
            {children}
          </div>
        </body>
        <Footer />
      </html>
    </>
  );
}
